#!/usr/bin/env php
<?php
// Work in progress
//
require "./document-root/classes/loc-db-accessor.php";


$commands = "commands:\n" .
"  show migration\n" .
"  make migration [migration name]\n" .
"  do migration\n" .
"  undo migration\n";

if (count($argv) < 3) {
  echo $commands;
  exit(1);
}


switch ("$argv[1] $argv[2]") {
  case "make migration":
    if (count($argv) < 4) {
      echo "you must provide the name for the migration\n";
      exit(1);
    }
    $datetime = (new DateTime())->setTimezone(new DateTimeZone('Z'));
    $datetime_str = $datetime->format('Y-m-d\TH:i:sp');
    touch("database/migrations/$datetime_str-$argv[3].up.sql");
    touch("database/migrations/$datetime_str-$argv[3].down.sql");
    break;
  case "show migration":
    $db = LocDBAccessor::connect('./database/database.sqlite');
    $results = $db->query('SELECT * FROM migration_tbl')->fetchAll();
    echo "Migrations:\n";
    foreach($results as $result) {
      $results_arr = [$result['id'], $result['name'], $result['applied']];
      echo implode(' | ', $results_arr) . "\n";
    }
    echo "\n";
    break;
  default:
    echo $commands;
}
